### ISSUE TITLE
Multiline indent fix doesn't work as expected

### ISSUE THREAD

**Issue by m-iwanicki** [priv-kweihmann/oelint-adv#662]
## oelint version
6.6.0

## How to reproduce

* init empty git repository
* create files
    * `.pre-commit-config.yaml`

        ```yaml
        ---
        default_stages: [pre-commit]

        default_install_hook_types: [pre-commit, commit-msg]

        repos:
            - repo: https://github.com/priv-kweihmann/oelint-adv
            rev: 6.6.0
            hooks:
                - id: oelint-adv
                args: [--rulefile=.oelint-ruleset.json, --fix, --hide=info, --quiet]
        ```

    * `.oelint-ruleset.json`

        ```json
        {
            "oelint.vars.multilineident": "warning"
        }
        ```

    * `test_git.bb`

        ```bitbake
        SUMMARY = "test"
        DESCRIPTION = "test file"
        HOMEPAGE = "https://example.org"
        LICENSE = "CLOSED"

        DEPENDS:append = " \
            openssl \
            flashrom \
            "

        SRC_URI = "file://test"
        ```
* commit all files with `--no-verify` to see diff easier
* run `pre-commit run -a`

## Outcome

```
Advanced oelint..........................................................Failed
- hook id: oelint-adv
- exit code: 1
- files were modified by this hook

/oelint-test/test_git.bb:8:warning:oelint.vars.multilineident:On a multiline assignment, line indent is desirable. 0 set, 4 desirable [branch:true]
```

Somehow oelint thinks there is no indent (`0 set, 4 desirable`). There is also "fix" that's being applied that doesn't fix anything:

```diff
diff --git a/test_git.bb b/test_git.bb
index 62b16e2bbaec..c49b968a7f99 100644
--- a/test_git.bb
+++ b/test_git.bb
@@ -5,7 +5,7 @@ LICENSE = "CLOSED"

 DEPENDS:append = " \
     openssl \
-    flashrom \
-    "
+flashrom \
+   "

 SRC_URI = "file://test"
```

## Variations

If we start with

```bitbake
DEPENDS:append = " \
    openssl \
    flashrom \
"
```

then we end up with

```diff
diff --git a/test_git.bb b/test_git.bb
index 77653a930f0f..a32d9460944f 100644
--- a/test_git.bb
+++ b/test_git.bb
@@ -5,7 +5,7 @@ LICENSE = "CLOSED"

 DEPENDS:append = " \
     openssl \
-    flashrom \
+    flashrom\
 "
```

and no `warning:oelint.vars.multilineident` warning

The only configuration that works is

```bitbake
DEPENDS:append = "\
    openssl\
    flashrom\
"
```

## Expected outcome

Based on https://docs.yoctoproject.org/contributor-guide/recipe-style-guide.html#variable-formatting I would expect examples below to work

```bitbake
DEPENDS:append = " \
                  openssl \
                  flashrom \
                  "
```

```bitbake
DEPENDS = "openssl \
           flashrom \
           "
```

And based on example recipes in poky

```bitbake
DEPENDS = " \
    openssl \
    flashrom \
    "
```

And maybe

```bitbake
DEPENDS = " \
    openssl \
    flashrom \
"
```

Though it should probably be configurable so repository can keep consistent indenting.
